[metadata]
name = hardware
summary = Hardware detection and classification utilities
description_file =
    README.rst
author = eNovance
author_email = licensing@enovance.com
home_page = https://github.com/redhat-cip/hardware
python_requires = >=3.10
classifier =
    Topic :: System :: Hardware
    Intended Audience :: Information Technology
    Intended Audience :: System Administrators
    License :: OSI Approved :: Apache Software License
    Operating System :: POSIX :: Linux
    Programming Language :: Python
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Programming Language :: Python :: 3.13
    Programming Language :: Python :: 3.14

[files]
packages =
    hardware

[entry_points]
console_scripts =
    hardware-detect = hardware.detect:main
